[tool.poetry]
name = "r"
version = "0.1.0"
description = ""
authors = ["alena"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^6.2.4"
black = "^21.5b1"
flake8 = "poetry install"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
